# Generated by Django 4.2.4 on 2023-09-09 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universitycampus',
            old_name='campus_id',
            new_name='campus',
        ),
    ]
